const projects = [
  {
    id: 1,
    type: 'library',
    stack: ['typescript'],
    title: 'Generate Passphrase',
    description: 'Secure random passphrase for Node.js',
    repository: 'https://github.com/aldy505/generate-passphrase',
    role: 'author',
  },
  {
    id: 2,
    type: 'library',
    stack: ['go'],
    title: 'Bob',
    description: 'SQL query builder as an extension of Squirrel',
    repository: 'https://github.com/aldy505/bob',
    role: 'author',
  },
  {
    id: 3,
    type: 'library',
    stack: ['go'],
    title: 'PHC Crypto',
    description: 'Password hashing with Argon2, Bcrypt, Scrypt, and PBKDF2 simplified',
    repository: 'https://github.com/aldy505/phc-crypto',
    role: 'author',
  },
  {
    id: 4,
    type: 'library',
    stack: ['typescript'],
    title: 'Malibu',
    description: 'Framework-agnostic CSRF middleware for modern Node.js applications',
    repository: 'https://github.com/tinyhttp/malibu',
    role: 'author',
  },
  {
    id: 5,
    type: 'application',
    stack: ['go', 'typescript', 'svelte', 'tailwindcss', 'postgresql', 'redis'],
    title: 'Jokes Bapak2',
    description: 'Image API for serving Indonesian dad jokes',
    repository: 'https://github.com/aldy505/jokes-bapak2',
    website: 'http://jokesbapak2.pages.dev/',
    role: 'author',
  },
  {
    id: 6,
    type: 'library',
    stack: ['typescript'],
    title: 'Tinyhttp',
    description: 'Typescript-based framework as a replacement for Express',
    repository: 'https://github.com/tinyhttp/tinyhttp',
    role: 'contributor',
  },
  {
    id: 7,
    type: 'application',
    stack: ['vuejs', 'tailwindcss'],
    title: 'ARCET Creative Visual Studio',
    description: 'Website for ARCET',
    website: 'https://www.arcet.id',
    role: 'author',
  },
  {
    id: 8,
    type: 'application',
    stack: ['vuejs', 'bootstrap'],
    title: 'Pesanyuk',
    description: 'Store-management application for Indonesian small to medium businesses',
    website: 'https://pesanyuk.id',
    role: 'contributor',
  },
  {
    id: 9,
    type: 'application',
    stack: ['javascript', 'redis', 'mongodb'],
    title: 'Teknologi Umum Bot',
    description: 'A simple telegram bot for managing daily poll & programming-related quizes',
    repository: 'https://github.com/teknologi-umum/bot',
    role: 'author',
  },
];

export default projects;
