name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup nodejs
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.x

      - name: Installling dependencies
        run: npm install

      - name: Lint
        run: npx eslint --ext .ts,.tsx,.js,.jsx --ignore-path .gitignore .

      - name: Build
        run: npm run generate

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
